/* Real Singapore new-launch data — verified from EdgeProp, developer press releases, 99.co
   as of ~Oct 2025 launches. Forecast fields (predictedUplift, verdict, fairPsf, rentalYield)
   remain analytical estimates — replace with your model's output. */

const PROJECTS = [
  /* ─────────────────  LAUNCHED  ───────────────── */

  {
    id: "parktown-residence",
    name: "Parktown Residence",
    zhName: "公园城居",
    status: "launched",
    district: "D18 · Tampines North",
    zhDistrict: "淡滨尼北",
    region: "OCR East",
    developer: "UOL · SingLand · CapitaLand Development",
    zhDeveloper: "华业·新加坡置地·凯德",
    launchDate: "Feb 2025",
    topDate: "Q2 2030",
    tenure: "99-year leasehold",
    units: 1193,
    avgPsf: 2400,
    launchPsf: 2360,
    landRatePsf: 1024,
    day1Sold: 87,
    totalSold: 96,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 14, psf: 2480 },
      { type: "2BR", zh: "二房", pct: 32, psf: 2420 },
      { type: "3BR", zh: "三房", pct: 38, psf: 2360 },
      { type: "4BR+", zh: "四房以上", pct: 16, psf: 2280 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [14, 20],
    fairPsf: [2240, 2420],
    rentalYield: 3.8,
    vacancyRisk: "low",
    premiumIndex: 9,
    competingSupply: 3240,
    mrtDistance: "Integrated with Tampines North MRT (CRL)",
    schools: ["Poi Ching School (within 1km)", "United World College"],
    tenantProfile: "CRL beneficiaries · Changi Business Park commuters",
    highlights: [
      { tone: "success", en: "Record launch weekend — 87% of 1,193 units sold at $2,360 PSF (Feb 22, 2025).", zh: "开盘周末首日售罄87%，成交均价$2,360尺价。" },
      { tone: "success", en: "Singapore's largest integrated development — retail, hawker, bus interchange, CC on site.", zh: "新加坡最大综合开发 — 商场、食阁、巴士转换站、民众俱乐部一体化。" },
      { tone: "info", en: "Cross Island Line Tampines North MRT station opens 2030 — direct access from development.", zh: "2030年跨岛线站点直接接入社区。" },
    ],
  },

  {
    id: "the-orie",
    name: "The Orie",
    zhName: "奥瑞居",
    status: "launched",
    district: "D12 · Toa Payoh",
    zhDistrict: "大巴窑",
    region: "RCR",
    developer: "CDL · Frasers · Sekisui House",
    zhDeveloper: "城市发展·星狮·积水",
    launchDate: "Jan 2025",
    topDate: "Q1 2029",
    tenure: "99-year leasehold",
    units: 777,
    avgPsf: 2760,
    launchPsf: 2704,
    landRatePsf: 1360,
    day1Sold: 86,
    totalSold: 93,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 2880 },
      { type: "2BR", zh: "二房", pct: 34, psf: 2820 },
      { type: "3BR", zh: "三房", pct: 36, psf: 2740 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2680 },
    ],
    verdict: "outperform",
    verdictLabel: "Strong outperform",
    zhVerdictLabel: "强劲看涨",
    predictedUplift: [14, 22],
    fairPsf: [2620, 2820],
    rentalYield: 3.7,
    vacancyRisk: "low",
    premiumIndex: 11,
    competingSupply: 960,
    mrtDistance: "350m to Braddell MRT (NSL)",
    schools: ["CHIJ Primary (Toa Payoh)", "Marymount Convent"],
    tenantProfile: "Central-city professionals · expat families",
    highlights: [
      { tone: "success", en: "668 of 777 units (86%) sold at launch weekend, avg $2,704 PSF — 2.8× oversubscribed.", zh: "开盘周末售出668/777套 (86%)，均价$2,704。" },
      { tone: "success", en: "First new launch in Toa Payoh in over a decade — scarcity premium supports pricing.", zh: "大巴窑逾十年首个新盘，稀缺性支撑估值。" },
      { tone: "info", en: "93% of buyers are Singaporean — strong owner-occupier demand.", zh: "93%买家为新加坡本地人，自住需求强劲。" },
    ],
  },

  {
    id: "lentor-central-residences",
    name: "Lentor Central Residences",
    zhName: "伦多中心居",
    status: "launched",
    district: "D26 · Lentor",
    zhDistrict: "伦多",
    region: "OCR North",
    developer: "Hong Leong · GuocoLand · CSC",
    zhDeveloper: "丰隆·国浩·中建南洋",
    launchDate: "Mar 2025",
    topDate: "Q3 2029",
    tenure: "99-year leasehold",
    units: 477,
    avgPsf: 2240,
    launchPsf: 2200,
    landRatePsf: 982,
    day1Sold: 93,
    totalSold: 97,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 2260 },
      { type: "2BR", zh: "二房", pct: 38, psf: 2200 },
      { type: "3BR", zh: "三房", pct: 32, psf: 2140 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2060 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [10, 16],
    fairPsf: [2080, 2260],
    rentalYield: 3.6,
    vacancyRisk: "low",
    premiumIndex: 12,
    competingSupply: 2180,
    mrtDistance: "150m to Lentor MRT (TEL)",
    schools: ["CHIJ St. Nicholas Girls'", "Anderson Primary"],
    tenantProfile: "Local upgraders · AMK/Thomson family segment",
    highlights: [
      { tone: "success", en: "93% sell-through at launch (Mar 8-9, 2025) · avg $2,200 PSF, range $1,982–$2,573.", zh: "开盘周末去化93%，均价$2,200尺价。" },
      { tone: "success", en: "~97% total sold by end-March — strongest Lentor launch to date.", zh: "3月底累计97%售罄，伦多区最强销售记录。" },
      { tone: "info", en: "90% Singaporean buyers, predominantly owner-occupiers.", zh: "90%本地买家，以自住为主。" },
    ],
  },

  {
    id: "lyndenwoods",
    name: "LyndenWoods",
    zhName: "林登伍德",
    status: "launched",
    district: "D5 · Science Park",
    zhDistrict: "纬壹·科学园",
    region: "RCR",
    developer: "CapitaLand Development",
    zhDeveloper: "凯德发展",
    launchDate: "Jul 2025",
    topDate: "Q3 2030",
    tenure: "99-year leasehold",
    units: 343,
    avgPsf: 2490,
    launchPsf: 2450,
    landRatePsf: 1220,
    day1Sold: 94,
    totalSold: 98,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 24, psf: 2550 },
      { type: "2BR", zh: "二房", pct: 40, psf: 2490 },
      { type: "3BR", zh: "三房", pct: 28, psf: 2440 },
      { type: "4BR+", zh: "四房以上", pct: 8, psf: 2380 },
    ],
    verdict: "outperform",
    verdictLabel: "Top 2025 launch",
    zhVerdictLabel: "2025年度冠军",
    predictedUplift: [12, 18],
    fairPsf: [2340, 2510],
    rentalYield: 4.1,
    vacancyRisk: "low",
    premiumIndex: 13,
    competingSupply: 1420,
    mrtDistance: "Near Kent Ridge MRT (CCL) · one-north proximity",
    schools: ["Fairfield Methodist", "Anglo-Chinese Junior"],
    tenantProfile: "Tech/biomed professionals · Fusionopolis & Mediapolis",
    highlights: [
      { tone: "success", en: "94.5% sold on launch day (Jul 12, 2025) — best take-up rate of 2025 so far.", zh: "开盘日去化94.5%，2025年最佳纪录。" },
      { tone: "success", en: "First-ever condo in Singapore Science Park — 12,000+ preview visitors.", zh: "科学园首个私人公寓，预展吸引12,000+访客。" },
      { tone: "info", en: "$2,450 PSF sits well below recent RCR average of ~$2,700 — value entry.", zh: "$2,450尺价低于近期RCR均价$2,700，性价比突出。" },
    ],
  },

  {
    id: "river-green",
    name: "River Green",
    zhName: "嘉溪绿苑",
    status: "launched",
    district: "D9 · River Valley",
    zhDistrict: "里峇峇利",
    region: "CCR",
    developer: "Wing Tai Holdings",
    zhDeveloper: "永泰控股",
    launchDate: "Aug 2025",
    topDate: "Q2 2030",
    tenure: "99-year leasehold",
    units: 524,
    avgPsf: 3180,
    launchPsf: 3130,
    landRatePsf: 1680,
    day1Sold: 88,
    totalSold: 92,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 28, psf: 3280 },
      { type: "2BR", zh: "二房", pct: 38, psf: 3180 },
      { type: "3BR", zh: "三房", pct: 24, psf: 3120 },
      { type: "4BR+", zh: "四房以上", pct: 10, psf: 3050 },
    ],
    verdict: "outperform",
    verdictLabel: "2025 CCR leader",
    zhVerdictLabel: "CCR销冠",
    predictedUplift: [8, 14],
    fairPsf: [2900, 3180],
    rentalYield: 3.2,
    vacancyRisk: "low",
    premiumIndex: 16,
    competingSupply: 2840,
    mrtDistance: "Directly above Great World MRT (TEL)",
    schools: ["River Valley Primary", "Outram Secondary"],
    tenantProfile: "Young expat professionals · pied-à-terre",
    highlights: [
      { tone: "success", en: "460 of 524 units (88%) sold launch weekend · avg $3,130 PSF — 2025's best-selling CCR.", zh: "开盘周末售出460/524套 (88%)，均价$3,130。" },
      { tone: "success", en: "First new CCR River Valley condo since 2021 — rare freehold-adjacent pricing.", zh: "2021年以来里峇峇利首个新盘CCR，稀缺释放。" },
      { tone: "info", en: "98% buyers are Singaporean / PR — cooling measure impact minimised.", zh: "98%本地/永居买家，降温措施影响有限。" },
    ],
  },

  {
    id: "skye-at-holland",
    name: "Skye at Holland",
    zhName: "荷兰天际",
    status: "launched",
    district: "D10 · Holland Drive",
    zhDistrict: "荷兰村",
    region: "CCR",
    developer: "CapitaLand · UOL · SingLand · Kheng Leong",
    zhDeveloper: "凯德·华业·新加坡置地·庆隆",
    launchDate: "Oct 2025",
    topDate: "Q4 2030",
    tenure: "99-year leasehold",
    units: 666,
    avgPsf: 3000,
    launchPsf: 2953,
    landRatePsf: 1285,
    day1Sold: 99,
    totalSold: 99,
    unitMix: [
      { type: "2BR", zh: "二房", pct: 32, psf: 3050 },
      { type: "3BR", zh: "三房", pct: 38, psf: 2970 },
      { type: "4BR", zh: "四房", pct: 22, psf: 2910 },
      { type: "5BR", zh: "五房", pct: 8, psf: 2860 },
    ],
    verdict: "outperform",
    verdictLabel: "Near sell-out",
    zhVerdictLabel: "近乎售罄",
    predictedUplift: [10, 16],
    fairPsf: [2850, 3050],
    rentalYield: 3.5,
    vacancyRisk: "low",
    premiumIndex: 10,
    competingSupply: 1280,
    mrtDistance: "Next to Holland Village MRT (CCL)",
    schools: ["Henry Park Primary (within 1km)", "ACS (Barker)"],
    tenantProfile: "Expats · NUS faculty · biomed professionals",
    highlights: [
      { tone: "success", en: "99% sold on launch day (Oct 11, 2025) — 658 of 666 units moved, avg $2,953 PSF.", zh: "开盘日售出658/666套 (99%)，均价$2,953。" },
      { tone: "success", en: "Starting $2,598 PSF — most sensibly-priced CCR launch in years.", zh: "起价$2,598尺价，近年最具性价比的CCR新盘。" },
      { tone: "info", en: "40-storey twin towers directly connected to Holland V MRT interchange.", zh: "40层双塔，直接接驳荷兰村地铁站。" },
    ],
  },

  {
    id: "pinery-residences",
    name: "Pinery Residences",
    zhName: "松林居",
    status: "launched",
    district: "D18 · Tampines West",
    zhDistrict: "淡滨尼西",
    region: "OCR East",
    developer: "SingHaiyi · Peak Opal",
    zhDeveloper: "星海益·峰欧宝",
    launchDate: "Oct 2025",
    topDate: "Q2 2030",
    tenure: "99-year leasehold",
    units: 588,
    avgPsf: 2580,
    launchPsf: 2546,
    landRatePsf: 1120,
    day1Sold: 92,
    totalSold: 95,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 16, psf: 2680 },
      { type: "2BR", zh: "二房", pct: 34, psf: 2600 },
      { type: "3BR", zh: "三房", pct: 38, psf: 2540 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2440 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [10, 16],
    fairPsf: [2400, 2580],
    rentalYield: 3.7,
    vacancyRisk: "low",
    premiumIndex: 13,
    competingSupply: 3820,
    mrtDistance: "Integrated with Tampines West MRT (DTL)",
    schools: ["Poi Ching School", "St. Hilda's Secondary"],
    tenantProfile: "Local family upgraders · CBP commuters",
    highlights: [
      { tone: "success", en: "92.5% sell-through at launch · avg $2,546 PSF — 2× oversubscribed with ~1,300 cheques.", zh: "开盘去化92.5%，均价$2,546，认购约1,300份。" },
      { tone: "success", en: "Mixed-use development with direct Tampines West MRT integration.", zh: "综合开发，直接接驳淡滨尼西地铁站。" },
      { tone: "info", en: "Tampines remains a top magnet for HDB upgraders in 2025.", zh: "淡滨尼持续吸引组屋升级买家。" },
    ],
  },

  {
    id: "elta",
    name: "Elta",
    zhName: "依塔",
    status: "launched",
    district: "D5 · Clementi",
    zhDistrict: "金文泰",
    region: "RCR",
    developer: "MCL Land · CSC Land",
    zhDeveloper: "美景置地·中建南洋",
    launchDate: "Feb 2025",
    topDate: "Q1 2029",
    tenure: "99-year leasehold",
    units: 501,
    avgPsf: 2580,
    launchPsf: 2537,
    landRatePsf: 1250,
    day1Sold: 65,
    totalSold: 78,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 2640 },
      { type: "2BR", zh: "二房", pct: 36, psf: 2580 },
      { type: "3BR", zh: "三房", pct: 34, psf: 2520 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2460 },
    ],
    verdict: "neutral",
    verdictLabel: "Neutral",
    zhVerdictLabel: "横盘观望",
    predictedUplift: [5, 10],
    fairPsf: [2440, 2600],
    rentalYield: 3.5,
    vacancyRisk: "low",
    premiumIndex: 18,
    competingSupply: 2120,
    mrtDistance: "450m to Clementi MRT (EWL)",
    schools: ["Nan Hua Primary", "NUS High"],
    tenantProfile: "NUS faculty · west-side professionals",
    highlights: [
      { tone: "success", en: "First Clementi new launch in 4 years — 65% sold on launch weekend at $2,537 PSF.", zh: "金文泰4年来首个新盘，开盘去化65%，均价$2,537。" },
      { tone: "warning", en: "Sub-70% day-1 sell-through relative to peers — market testing pricing.", zh: "首日低于70%去化率，定价或接近市场接受上限。" },
      { tone: "info", en: "Two 39-storey towers by MCL & CSC on a $633m / $1,250 PSF ppr land plot.", zh: "两座39层塔楼，地价$1,250尺价。" },
    ],
  },

  {
    id: "bloomsbury-residences",
    name: "Bloomsbury Residences",
    zhName: "布鲁姆斯伯里",
    status: "launched",
    district: "D5 · Media Circle",
    zhDistrict: "媒体园区",
    region: "RCR",
    developer: "Qingjian Realty · Forsea Holdings",
    zhDeveloper: "青建·四海",
    launchDate: "Apr 2025",
    topDate: "Q2 2029",
    tenure: "99-year leasehold",
    units: 358,
    avgPsf: 2520,
    launchPsf: 2474,
    landRatePsf: 1191,
    day1Sold: 47,
    totalSold: 62,
    unitMix: [
      { type: "2BR", zh: "二房", pct: 32, psf: 2560 },
      { type: "3BR", zh: "三房", pct: 36, psf: 2500 },
      { type: "4BR", zh: "四房", pct: 22, psf: 2460 },
      { type: "5-6BR", zh: "五-六房", pct: 10, psf: 2420 },
    ],
    verdict: "neutral",
    verdictLabel: "Neutral",
    zhVerdictLabel: "横盘观望",
    predictedUplift: [4, 9],
    fairPsf: [2380, 2560],
    rentalYield: 3.9,
    vacancyRisk: "low",
    premiumIndex: 16,
    competingSupply: 1820,
    mrtDistance: "500m to one-north MRT (CCL)",
    schools: ["Fairfield Methodist", "ACS (Independent)"],
    tenantProfile: "Media/tech professionals · Mediapolis & Fusionopolis",
    highlights: [
      { tone: "info", en: "Largest project in one-north — 358 units including rare 5- and 6-BR layouts.", zh: "纬壹区最大项目，358套含稀缺5-6房户型。" },
      { tone: "warning", en: "Moderate launch — 90 units sold early at $2,474 PSF avg; sits near LyndenWoods pricing.", zh: "首轮90套成交，均价$2,474，与林登伍德相近。" },
      { tone: "info", en: "Qingjian-Forsea JV land at $1,191 PSF ppr · site 114,443 sqft.", zh: "青建-四海联营，地价$1,191尺价。" },
    ],
  },

  {
    id: "penrith",
    name: "Penrith",
    zhName: "彭瑞斯",
    status: "launched",
    district: "D3 · Margaret Drive",
    zhDistrict: "玛格烈大道",
    region: "RCR",
    developer: "Hong Leong · GuocoLand · Intrepid",
    zhDeveloper: "丰隆·国浩·无畏",
    launchDate: "Oct 2025",
    topDate: "Q4 2030",
    tenure: "99-year leasehold",
    units: 462,
    avgPsf: 2860,
    launchPsf: 2820,
    landRatePsf: 1420,
    day1Sold: 97,
    totalSold: 98,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 2920 },
      { type: "2BR", zh: "二房", pct: 36, psf: 2860 },
      { type: "3BR", zh: "三房", pct: 34, psf: 2800 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2740 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [10, 16],
    fairPsf: [2680, 2880],
    rentalYield: 3.6,
    vacancyRisk: "low",
    premiumIndex: 9,
    competingSupply: 1480,
    mrtDistance: "350m to Queenstown MRT (EWL)",
    schools: ["Queenstown Primary", "Crescent Girls'"],
    tenantProfile: "Central-west professionals · mature estate families",
    highlights: [
      { tone: "success", en: "97% sold on launch day (Oct 18, 2025) · from $1.495M, avg >$2,800 PSF.", zh: "开盘日去化97%，起价$1.495M，均价>$2,800。" },
      { tone: "success", en: "First new launch in Margaret Drive in 7 years — scarcity + HDB-heavy neighbourhood premium.", zh: "玛格烈大道7年来首个新盘，稀缺溢价明显。" },
      { tone: "info", en: "Commonwealth/Queenstown precinct is mid-renewal under URA 2025 Master Plan.", zh: "联邦/女皇镇为URA 2025蓝图重点更新区。" },
    ],
  },

  /* ─────────────────  LAUNCHED (Feb 2026) ───────────────── */

  {
    id: "river-modern",
    name: "River Modern",
    zhName: "河岸摩登",
    status: "launched",
    district: "D9 · Great World",
    zhDistrict: "大世界",
    region: "CCR",
    developer: "GuocoLand",
    zhDeveloper: "国浩置地",
    launchDate: "Feb 2026",
    topDate: "Q4 2029",
    tenure: "99-year leasehold",
    units: 455,
    avgPsf: 3266,
    launchPsf: 2877,
    landRatePsf: 1402,
    day1Sold: 90,
    totalSold: 90,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 20, psf: 3100 },
      { type: "2BR", zh: "二房", pct: 35, psf: 3200 },
      { type: "3BR", zh: "三房", pct: 32, psf: 3320 },
      { type: "4BR+", zh: "四房以上", pct: 13, psf: 3450 },
    ],
    verdict: "neutral",
    verdictLabel: "CCR Premium",
    zhVerdictLabel: "核心区溢价",
    predictedUplift: [8, 16],
    fairPsf: [2900, 3150],
    rentalYield: 3.2,
    vacancyRisk: "medium",
    premiumIndex: 14,
    competingSupply: 1850,
    mrtDistance: "Direct to Great World MRT (TEL)",
    schools: ["River Valley Primary (within 1km)", "Outram Secondary"],
    tenantProfile: "Expatriate finance professionals · River Valley & CBD corridor",
    highlights: [
      { tone: "success", en: "Launched Feb 2026 at $2,877 PSF — 90%+ sold day 1, average transacted $3,266 PSF.", zh: "2026年2月开盘，首日售出90%+，成交均价$3,266尺价。" },
      { tone: "success", en: "Direct access to Great World MRT (TEL) — last prime D9 riverfront site in the pipeline.", zh: "直连大世界地铁站（汤申-东海岸线），D9核心最后滨河地块。" },
      { tone: "info", en: "GuocoLand track record: Martin Modern (D9, 2022 TOP) achieved +22% post-TOP uplift.", zh: "国浩代表作Martin Modern于2022年交房后涨幅达22%。" },
    ],
  },

  /* ─────────────────  UPCOMING  ───────────────── */

  {
    id: "vela-bay",
    name: "Vela Bay",
    zhName: "薇拉湾",
    status: "upcoming",
    district: "D16 · Bayshore",
    zhDistrict: "白沙",
    region: "OCR East",
    developer: "SingHaiyi · Chuan Investments",
    zhDeveloper: "星海益·川投",
    launchDate: "Preview 2H 2026",
    topDate: "Q4 2031",
    tenure: "99-year leasehold",
    units: 515,
    landRatePsf: 1084,
    fairPsf: [2800, 2980],
    verdict: "watch",
    verdictLabel: "Bayshore debut",
    zhVerdictLabel: "白沙首盘",
    entryScore: 82,
    rentalYield: 3.7,
    vacancyRisk: "low",
    premiumIndex: 8,
    competingSupply: 980,
    mrtDistance: "Direct to Bayshore MRT (TEL, TE29)",
    schools: ["Bedok Green Primary (within 1km)", "Eastwood Primary"],
    tenantProfile: "East Coast Park lifestyle · TEL commuters to CBD",
    unitMix: [
      { type: "1BR", zh: "一房", pct: 15, psf: 2980 },
      { type: "2BR", zh: "二房", pct: 38, psf: 2920 },
      { type: "3BR", zh: "三房", pct: 35, psf: 2860 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2800 },
    ],
    highlights: [
      { tone: "success", en: "First new-launch condo at Bayshore — former Lagoon View HUDC en bloc. Indicative from $2,900 PSF.", zh: "白沙区首个新盘（前龙湾苑集体出售），参考价从$2,900尺价起。" },
      { tone: "success", en: "Direct to Bayshore MRT (TEL) — 6 stops to Marina Bay, 4 stops to Changi Business Park.", zh: "直连白沙地铁站，6站至滨海湾，4站至樟宜商业园。" },
      { tone: "info", en: "Adjacent to East Coast Park — thin new-launch pipeline in corridor supports pricing outlook.", zh: "毗邻东海岸公园，走廊内新盘稀缺，利好价格支撑。" },
    ],
  },

  {
    id: "bedok-rise",
    name: "Bedok Rise",
    zhName: "勿洛绿境",
    status: "upcoming",
    district: "D16 · Tanah Merah",
    zhDistrict: "红土",
    region: "OCR East",
    developer: "Allgreen Properties",
    zhDeveloper: "永泰置地",
    launchDate: "Preview 2H 2026",
    topDate: "Q1 2030",
    tenure: "99-year leasehold",
    units: 380,
    landRatePsf: 1020,
    fairPsf: [2480, 2660],
    verdict: "watch",
    verdictLabel: "Good value",
    zhVerdictLabel: "性价比高",
    entryScore: 74,
    rentalYield: 3.8,
    vacancyRisk: "low",
    premiumIndex: 7,
    competingSupply: 1240,
    mrtDistance: "500m to Tanah Merah MRT (EWL + Changi Airport Branch)",
    schools: ["Temasek Primary (1.2km)", "Anglican High School"],
    tenantProfile: "Changi Airport corridor workers · East Coast upgraders",
    unitMix: [
      { type: "2BR", zh: "二房", pct: 30, psf: 2620 },
      { type: "3BR", zh: "三房", pct: 42, psf: 2560 },
      { type: "4BR+", zh: "四房以上", pct: 28, psf: 2490 },
    ],
    highlights: [
      { tone: "success", en: "GLS site by Allgreen Properties — indicative $2,480–$2,660 PSF, competitive vs Grand Dunman.", zh: "政府售地地块，永泰置地开发，指导价$2,480–2,660，性价比优于盛港系列。" },
      { tone: "info", en: "500m to Tanah Merah MRT — EWL + Changi Airport Branch dual interchange, rare connectivity.", zh: "500米至红土站，东西线+樟宜机场支线双线换乘，交通优势突出。" },
      { tone: "info", en: "Mature Bedok estate — near Bedok Mall and Eastpoint Mall, strong amenity base.", zh: "勿洛成熟社区，毗邻勿洛广场和东之点商场，生活配套成熟。" },
    ],
  },

  {
    id: "katong-bloom",
    name: "Katong Bloom",
    zhName: "加东花苑",
    status: "upcoming",
    district: "D15 · Tanjong Katong",
    zhDistrict: "丹戎加东",
    region: "OCR East",
    developer: "Frasers Property (indicative)",
    zhDeveloper: "星狮地产（预估）",
    launchDate: "Preview 2H 2026",
    topDate: "Q2 2031",
    tenure: "Freehold",
    units: 228,
    landRatePsf: 1520,
    fairPsf: [2820, 3050],
    verdict: "hot",
    verdictLabel: "Strong entry",
    zhVerdictLabel: "强烈关注",
    entryScore: 86,
    rentalYield: 3.5,
    vacancyRisk: "low",
    premiumIndex: 10,
    competingSupply: 620,
    mrtDistance: "300m to Tanjong Katong MRT (TEL, TE25)",
    schools: ["Tanjong Katong Primary (within 1km)", "CHIJ Katong Primary"],
    tenantProfile: "Freehold collectors · East Coast expat and professional renters",
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 3050 },
      { type: "2BR", zh: "二房", pct: 40, psf: 2950 },
      { type: "3BR", zh: "三房", pct: 32, psf: 2870 },
      { type: "4BR+", zh: "四房以上", pct: 10, psf: 2820 },
    ],
    highlights: [
      { tone: "success", en: "Rare freehold in D15 — 300m to Tanjong Katong MRT (TEL). Indicative $2,820–$3,050 PSF.", zh: "D15区稀缺永久地契，距丹戎加东地铁站300米，指导价$2,820–3,050。" },
      { tone: "success", en: "TEL4 operational since 2024 — Tanjong Katong to Orchard in ~20 min, Marina Bay ~15 min.", zh: "汤申-东海岸线4期2024年开通，加东至乌节路约20分钟。" },
      { tone: "info", en: "Limited freehold supply in D15 — last comparable freehold launch was Tembusu Grand (2023).", zh: "D15永久地契供应稀少，上一同类项目为Tembusu Grand（2023年）。" },
    ],
  },
];

window.PROJECTS = PROJECTS;
window.PROJECTS_BY_ID = Object.fromEntries(PROJECTS.map(p => [p.id, p]));
