/* Real Singapore new-launch data — verified from EdgeProp, developer press releases, 99.co
   as of ~Oct 2025 launches. Forecast fields (predictedUplift, verdict, fairPsf, rentalYield)
   remain analytical estimates — replace with your model's output. */

const PROJECTS = [
  /* ─────────────────  LAUNCHED  ───────────────── */

  {
    id: "parktown-residence",
    name: "Parktown Residence",
    zhName: "公园城居",
    status: "launched",
    district: "D18 · Tampines North",
    zhDistrict: "淡滨尼北",
    region: "OCR East",
    developer: "UOL · SingLand · CapitaLand Development",
    zhDeveloper: "华业·新加坡置地·凯德",
    launchDate: "Feb 2025",
    topDate: "Q2 2030",
    tenure: "99-year leasehold",
    units: 1193,
    avgPsf: 2400,
    launchPsf: 2360,
    landRatePsf: 1024,
    day1Sold: 87,
    totalSold: 96,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 14, psf: 2480 },
      { type: "2BR", zh: "二房", pct: 32, psf: 2420 },
      { type: "3BR", zh: "三房", pct: 38, psf: 2360 },
      { type: "4BR+", zh: "四房以上", pct: 16, psf: 2280 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [14, 20],
    fairPsf: [2240, 2420],
    rentalYield: 3.8,
    vacancyRisk: "low",
    premiumIndex: 9,
    competingSupply: 3240,
    mrtDistance: "Integrated with Tampines North MRT (CRL)",
    schools: ["Poi Ching School (within 1km)", "United World College"],
    tenantProfile: "CRL beneficiaries · Changi Business Park commuters",
    highlights: [
      { tone: "success", en: "Record launch weekend — 87% of 1,193 units sold at $2,360 PSF (Feb 22, 2025).", zh: "开盘周末首日售罄87%，成交均价$2,360尺价。" },
      { tone: "success", en: "Singapore's largest integrated development — retail, hawker, bus interchange, CC on site.", zh: "新加坡最大综合开发 — 商场、食阁、巴士转换站、民众俱乐部一体化。" },
      { tone: "info", en: "Cross Island Line Tampines North MRT station opens 2030 — direct access from development.", zh: "2030年跨岛线站点直接接入社区。" },
    ],
  },

  {
    id: "the-orie",
    name: "The Orie",
    zhName: "奥瑞居",
    status: "launched",
    district: "D12 · Toa Payoh",
    zhDistrict: "大巴窑",
    region: "RCR",
    developer: "CDL · Frasers · Sekisui House",
    zhDeveloper: "城市发展·星狮·积水",
    launchDate: "Jan 2025",
    topDate: "Q1 2029",
    tenure: "99-year leasehold",
    units: 777,
    avgPsf: 2760,
    launchPsf: 2704,
    landRatePsf: 1360,
    day1Sold: 86,
    totalSold: 93,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 2880 },
      { type: "2BR", zh: "二房", pct: 34, psf: 2820 },
      { type: "3BR", zh: "三房", pct: 36, psf: 2740 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2680 },
    ],
    verdict: "outperform",
    verdictLabel: "Strong outperform",
    zhVerdictLabel: "强劲看涨",
    predictedUplift: [14, 22],
    fairPsf: [2620, 2820],
    rentalYield: 3.7,
    vacancyRisk: "low",
    premiumIndex: 11,
    competingSupply: 960,
    mrtDistance: "350m to Braddell MRT (NSL)",
    schools: ["CHIJ Primary (Toa Payoh)", "Marymount Convent"],
    tenantProfile: "Central-city professionals · expat families",
    highlights: [
      { tone: "success", en: "668 of 777 units (86%) sold at launch weekend, avg $2,704 PSF — 2.8× oversubscribed.", zh: "开盘周末售出668/777套 (86%)，均价$2,704。" },
      { tone: "success", en: "First new launch in Toa Payoh in over a decade — scarcity premium supports pricing.", zh: "大巴窑逾十年首个新盘，稀缺性支撑估值。" },
      { tone: "info", en: "93% of buyers are Singaporean — strong owner-occupier demand.", zh: "93%买家为新加坡本地人，自住需求强劲。" },
    ],
  },

  {
    id: "lentor-central-residences",
    name: "Lentor Central Residences",
    zhName: "伦多中心居",
    status: "launched",
    district: "D26 · Lentor",
    zhDistrict: "伦多",
    region: "OCR North",
    developer: "Hong Leong · GuocoLand · CSC",
    zhDeveloper: "丰隆·国浩·中建南洋",
    launchDate: "Mar 2025",
    topDate: "Q3 2029",
    tenure: "99-year leasehold",
    units: 477,
    avgPsf: 2240,
    launchPsf: 2200,
    landRatePsf: 982,
    day1Sold: 93,
    totalSold: 97,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 2260 },
      { type: "2BR", zh: "二房", pct: 38, psf: 2200 },
      { type: "3BR", zh: "三房", pct: 32, psf: 2140 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2060 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [10, 16],
    fairPsf: [2080, 2260],
    rentalYield: 3.6,
    vacancyRisk: "low",
    premiumIndex: 12,
    competingSupply: 2180,
    mrtDistance: "150m to Lentor MRT (TEL)",
    schools: ["CHIJ St. Nicholas Girls'", "Anderson Primary"],
    tenantProfile: "Local upgraders · AMK/Thomson family segment",
    highlights: [
      { tone: "success", en: "93% sell-through at launch (Mar 8-9, 2025) · avg $2,200 PSF, range $1,982–$2,573.", zh: "开盘周末去化93%，均价$2,200尺价。" },
      { tone: "success", en: "~97% total sold by end-March — strongest Lentor launch to date.", zh: "3月底累计97%售罄，伦多区最强销售记录。" },
      { tone: "info", en: "90% Singaporean buyers, predominantly owner-occupiers.", zh: "90%本地买家，以自住为主。" },
    ],
  },

  {
    id: "lyndenwoods",
    name: "LyndenWoods",
    zhName: "林登伍德",
    status: "launched",
    district: "D5 · Science Park",
    zhDistrict: "纬壹·科学园",
    region: "RCR",
    developer: "CapitaLand Development",
    zhDeveloper: "凯德发展",
    launchDate: "Jul 2025",
    topDate: "Q3 2030",
    tenure: "99-year leasehold",
    units: 343,
    avgPsf: 2490,
    launchPsf: 2450,
    landRatePsf: 1220,
    day1Sold: 94,
    totalSold: 98,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 24, psf: 2550 },
      { type: "2BR", zh: "二房", pct: 40, psf: 2490 },
      { type: "3BR", zh: "三房", pct: 28, psf: 2440 },
      { type: "4BR+", zh: "四房以上", pct: 8, psf: 2380 },
    ],
    verdict: "outperform",
    verdictLabel: "Top 2025 launch",
    zhVerdictLabel: "2025年度冠军",
    predictedUplift: [12, 18],
    fairPsf: [2340, 2510],
    rentalYield: 4.1,
    vacancyRisk: "low",
    premiumIndex: 13,
    competingSupply: 1420,
    mrtDistance: "Near Kent Ridge MRT (CCL) · one-north proximity",
    schools: ["Fairfield Methodist", "Anglo-Chinese Junior"],
    tenantProfile: "Tech/biomed professionals · Fusionopolis & Mediapolis",
    highlights: [
      { tone: "success", en: "94.5% sold on launch day (Jul 12, 2025) — best take-up rate of 2025 so far.", zh: "开盘日去化94.5%，2025年最佳纪录。" },
      { tone: "success", en: "First-ever condo in Singapore Science Park — 12,000+ preview visitors.", zh: "科学园首个私人公寓，预展吸引12,000+访客。" },
      { tone: "info", en: "$2,450 PSF sits well below recent RCR average of ~$2,700 — value entry.", zh: "$2,450尺价低于近期RCR均价$2,700，性价比突出。" },
    ],
  },

  {
    id: "river-green",
    name: "River Green",
    zhName: "嘉溪绿苑",
    status: "launched",
    district: "D9 · River Valley",
    zhDistrict: "里峇峇利",
    region: "CCR",
    developer: "Wing Tai Holdings",
    zhDeveloper: "永泰控股",
    launchDate: "Aug 2025",
    topDate: "Q2 2030",
    tenure: "99-year leasehold",
    units: 524,
    avgPsf: 3180,
    launchPsf: 3130,
    landRatePsf: 1680,
    day1Sold: 88,
    totalSold: 92,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 28, psf: 3280 },
      { type: "2BR", zh: "二房", pct: 38, psf: 3180 },
      { type: "3BR", zh: "三房", pct: 24, psf: 3120 },
      { type: "4BR+", zh: "四房以上", pct: 10, psf: 3050 },
    ],
    verdict: "outperform",
    verdictLabel: "2025 CCR leader",
    zhVerdictLabel: "CCR销冠",
    predictedUplift: [8, 14],
    fairPsf: [2900, 3180],
    rentalYield: 3.2,
    vacancyRisk: "low",
    premiumIndex: 16,
    competingSupply: 2840,
    mrtDistance: "Directly above Great World MRT (TEL)",
    schools: ["River Valley Primary", "Outram Secondary"],
    tenantProfile: "Young expat professionals · pied-à-terre",
    highlights: [
      { tone: "success", en: "460 of 524 units (88%) sold launch weekend · avg $3,130 PSF — 2025's best-selling CCR.", zh: "开盘周末售出460/524套 (88%)，均价$3,130。" },
      { tone: "success", en: "First new CCR River Valley condo since 2021 — rare freehold-adjacent pricing.", zh: "2021年以来里峇峇利首个新盘CCR，稀缺释放。" },
      { tone: "info", en: "98% buyers are Singaporean / PR — cooling measure impact minimised.", zh: "98%本地/永居买家，降温措施影响有限。" },
    ],
  },

  {
    id: "skye-at-holland",
    name: "Skye at Holland",
    zhName: "荷兰天际",
    status: "launched",
    district: "D10 · Holland Drive",
    zhDistrict: "荷兰村",
    region: "CCR",
    developer: "CapitaLand · UOL · SingLand · Kheng Leong",
    zhDeveloper: "凯德·华业·新加坡置地·庆隆",
    launchDate: "Oct 2025",
    topDate: "Q4 2030",
    tenure: "99-year leasehold",
    units: 666,
    avgPsf: 3000,
    launchPsf: 2953,
    landRatePsf: 1285,
    day1Sold: 99,
    totalSold: 99,
    unitMix: [
      { type: "2BR", zh: "二房", pct: 32, psf: 3050 },
      { type: "3BR", zh: "三房", pct: 38, psf: 2970 },
      { type: "4BR", zh: "四房", pct: 22, psf: 2910 },
      { type: "5BR", zh: "五房", pct: 8, psf: 2860 },
    ],
    verdict: "outperform",
    verdictLabel: "Near sell-out",
    zhVerdictLabel: "近乎售罄",
    predictedUplift: [10, 16],
    fairPsf: [2850, 3050],
    rentalYield: 3.5,
    vacancyRisk: "low",
    premiumIndex: 10,
    competingSupply: 1280,
    mrtDistance: "Next to Holland Village MRT (CCL)",
    schools: ["Henry Park Primary (within 1km)", "ACS (Barker)"],
    tenantProfile: "Expats · NUS faculty · biomed professionals",
    highlights: [
      { tone: "success", en: "99% sold on launch day (Oct 11, 2025) — 658 of 666 units moved, avg $2,953 PSF.", zh: "开盘日售出658/666套 (99%)，均价$2,953。" },
      { tone: "success", en: "Starting $2,598 PSF — most sensibly-priced CCR launch in years.", zh: "起价$2,598尺价，近年最具性价比的CCR新盘。" },
      { tone: "info", en: "40-storey twin towers directly connected to Holland V MRT interchange.", zh: "40层双塔，直接接驳荷兰村地铁站。" },
    ],
  },

  {
    id: "pinery-residences",
    name: "Pinery Residences",
    zhName: "松林居",
    status: "launched",
    district: "D18 · Tampines West",
    zhDistrict: "淡滨尼西",
    region: "OCR East",
    developer: "Hoi Hup · Sunway MCL",
    zhDeveloper: "海葵·双威美景",
    launchDate: "Mar 2026",
    topDate: "Q2 2030",
    tenure: "99-year leasehold",
    units: 588,
    avgPsf: 2580,
    launchPsf: 2546,
    landRatePsf: 1120,
    day1Sold: 92,
    totalSold: 95,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 16, psf: 2680 },
      { type: "2BR", zh: "二房", pct: 34, psf: 2600 },
      { type: "3BR", zh: "三房", pct: 38, psf: 2540 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2440 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [10, 16],
    fairPsf: [2400, 2580],
    rentalYield: 3.7,
    vacancyRisk: "low",
    premiumIndex: 13,
    competingSupply: 3820,
    mrtDistance: "Integrated with Tampines West MRT (DTL)",
    schools: ["Poi Ching School", "St. Hilda's Secondary"],
    tenantProfile: "Local family upgraders · CBP commuters",
    highlights: [
      { tone: "success", en: "92.5% sell-through at launch · avg $2,546 PSF — 2× oversubscribed with ~1,300 cheques.", zh: "开盘去化92.5%，均价$2,546，认购约1,300份。" },
      { tone: "success", en: "Mixed-use development with direct Tampines West MRT integration.", zh: "综合开发，直接接驳淡滨尼西地铁站。" },
      { tone: "info", en: "Tampines remains a top magnet for HDB upgraders in 2025.", zh: "淡滨尼持续吸引组屋升级买家。" },
    ],
  },

  {
    id: "elta",
    name: "Elta",
    zhName: "依塔",
    status: "launched",
    district: "D5 · Clementi",
    zhDistrict: "金文泰",
    region: "RCR",
    developer: "MCL Land · CSC Land",
    zhDeveloper: "美景置地·中建南洋",
    launchDate: "Feb 2025",
    topDate: "Q1 2029",
    tenure: "99-year leasehold",
    units: 501,
    avgPsf: 2580,
    launchPsf: 2537,
    landRatePsf: 1250,
    day1Sold: 65,
    totalSold: 78,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 2640 },
      { type: "2BR", zh: "二房", pct: 36, psf: 2580 },
      { type: "3BR", zh: "三房", pct: 34, psf: 2520 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2460 },
    ],
    verdict: "neutral",
    verdictLabel: "Neutral",
    zhVerdictLabel: "横盘观望",
    predictedUplift: [5, 10],
    fairPsf: [2440, 2600],
    rentalYield: 3.5,
    vacancyRisk: "low",
    premiumIndex: 18,
    competingSupply: 2120,
    mrtDistance: "450m to Clementi MRT (EWL)",
    schools: ["Nan Hua Primary", "NUS High"],
    tenantProfile: "NUS faculty · west-side professionals",
    highlights: [
      { tone: "success", en: "First Clementi new launch in 4 years — 65% sold on launch weekend at $2,537 PSF.", zh: "金文泰4年来首个新盘，开盘去化65%，均价$2,537。" },
      { tone: "warning", en: "Sub-70% day-1 sell-through relative to peers — market testing pricing.", zh: "首日低于70%去化率，定价或接近市场接受上限。" },
      { tone: "info", en: "Two 39-storey towers by MCL & CSC on a $633m / $1,250 PSF ppr land plot.", zh: "两座39层塔楼，地价$1,250尺价。" },
    ],
  },

  {
    id: "bloomsbury-residences",
    name: "Bloomsbury Residences",
    zhName: "布鲁姆斯伯里",
    status: "launched",
    district: "D5 · Media Circle",
    zhDistrict: "媒体园区",
    region: "RCR",
    developer: "Qingjian Realty · Forsea Holdings",
    zhDeveloper: "青建·四海",
    launchDate: "Apr 2025",
    topDate: "Q2 2029",
    tenure: "99-year leasehold",
    units: 358,
    avgPsf: 2520,
    launchPsf: 2474,
    landRatePsf: 1191,
    day1Sold: 47,
    totalSold: 62,
    unitMix: [
      { type: "2BR", zh: "二房", pct: 32, psf: 2560 },
      { type: "3BR", zh: "三房", pct: 36, psf: 2500 },
      { type: "4BR", zh: "四房", pct: 22, psf: 2460 },
      { type: "5-6BR", zh: "五-六房", pct: 10, psf: 2420 },
    ],
    verdict: "neutral",
    verdictLabel: "Neutral",
    zhVerdictLabel: "横盘观望",
    predictedUplift: [4, 9],
    fairPsf: [2380, 2560],
    rentalYield: 3.9,
    vacancyRisk: "low",
    premiumIndex: 16,
    competingSupply: 1820,
    mrtDistance: "500m to one-north MRT (CCL)",
    schools: ["Fairfield Methodist", "ACS (Independent)"],
    tenantProfile: "Media/tech professionals · Mediapolis & Fusionopolis",
    highlights: [
      { tone: "info", en: "Largest project in one-north — 358 units including rare 5- and 6-BR layouts.", zh: "纬壹区最大项目，358套含稀缺5-6房户型。" },
      { tone: "warning", en: "Moderate launch — 90 units sold early at $2,474 PSF avg; sits near LyndenWoods pricing.", zh: "首轮90套成交，均价$2,474，与林登伍德相近。" },
      { tone: "info", en: "Qingjian-Forsea JV land at $1,191 PSF ppr · site 114,443 sqft.", zh: "青建-四海联营，地价$1,191尺价。" },
    ],
  },

  {
    id: "penrith",
    name: "Penrith",
    zhName: "彭瑞斯",
    status: "launched",
    district: "D3 · Margaret Drive",
    zhDistrict: "玛格烈大道",
    region: "RCR",
    developer: "Hong Leong · GuocoLand · Intrepid",
    zhDeveloper: "丰隆·国浩·无畏",
    launchDate: "Oct 2025",
    topDate: "Q4 2030",
    tenure: "99-year leasehold",
    units: 462,
    avgPsf: 2860,
    launchPsf: 2820,
    landRatePsf: 1420,
    day1Sold: 97,
    totalSold: 98,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 2920 },
      { type: "2BR", zh: "二房", pct: 36, psf: 2860 },
      { type: "3BR", zh: "三房", pct: 34, psf: 2800 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2740 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [10, 16],
    fairPsf: [2680, 2880],
    rentalYield: 3.6,
    vacancyRisk: "low",
    premiumIndex: 9,
    competingSupply: 1480,
    mrtDistance: "350m to Queenstown MRT (EWL)",
    schools: ["Queenstown Primary", "Crescent Girls'"],
    tenantProfile: "Central-west professionals · mature estate families",
    highlights: [
      { tone: "success", en: "97% sold on launch day (Oct 18, 2025) · from $1.495M, avg >$2,800 PSF.", zh: "开盘日去化97%，起价$1.495M，均价>$2,800。" },
      { tone: "success", en: "First new launch in Margaret Drive in 7 years — scarcity + HDB-heavy neighbourhood premium.", zh: "玛格烈大道7年来首个新盘，稀缺溢价明显。" },
      { tone: "info", en: "Commonwealth/Queenstown precinct is mid-renewal under URA 2025 Master Plan.", zh: "联邦/女皇镇为URA 2025蓝图重点更新区。" },
    ],
  },

  /* ─────────────────  LAUNCHED (Feb 2026) ───────────────── */

  {
    id: "river-modern",
    name: "River Modern",
    zhName: "河岸摩登",
    status: "launched",
    district: "D9 · Great World",
    zhDistrict: "大世界",
    region: "CCR",
    developer: "GuocoLand",
    zhDeveloper: "国浩置地",
    launchDate: "Feb 2026",
    topDate: "Q4 2029",
    tenure: "99-year leasehold",
    units: 455,
    avgPsf: 3266,
    launchPsf: 2877,
    landRatePsf: 1402,
    day1Sold: 90,
    totalSold: 90,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 20, psf: 3100 },
      { type: "2BR", zh: "二房", pct: 35, psf: 3200 },
      { type: "3BR", zh: "三房", pct: 32, psf: 3320 },
      { type: "4BR+", zh: "四房以上", pct: 13, psf: 3450 },
    ],
    verdict: "neutral",
    verdictLabel: "CCR Premium",
    zhVerdictLabel: "核心区溢价",
    predictedUplift: [8, 16],
    fairPsf: [2900, 3150],
    rentalYield: 3.2,
    vacancyRisk: "medium",
    premiumIndex: 14,
    competingSupply: 1850,
    mrtDistance: "Direct to Great World MRT (TEL)",
    schools: ["River Valley Primary (within 1km)", "Outram Secondary"],
    tenantProfile: "Expatriate finance professionals · River Valley & CBD corridor",
    highlights: [
      { tone: "success", en: "Launched Feb 2026 at $2,877 PSF — 90%+ sold day 1, average transacted $3,266 PSF.", zh: "2026年2月开盘，首日售出90%+，成交均价$3,266尺价。" },
      { tone: "success", en: "Direct access to Great World MRT (TEL) — last prime D9 riverfront site in the pipeline.", zh: "直连大世界地铁站（汤申-东海岸线），D9核心最后滨河地块。" },
      { tone: "info", en: "GuocoLand track record: Martin Modern (D9, 2022 TOP) achieved +22% post-TOP uplift.", zh: "国浩代表作Martin Modern于2022年交房后涨幅达22%。" },
    ],
  },

  /* ─────────────────  LAUNCHED (Apr 2026) ───────────────── */

  {
    id: "vela-bay",
    name: "Vela Bay",
    zhName: "薇拉湾",
    status: "launched",
    district: "D16 · Bayshore",
    zhDistrict: "白沙",
    region: "OCR East",
    developer: "SingHaiyi · Chuan Investments",
    zhDeveloper: "星海益·川投",
    launchDate: "Apr 2026",
    topDate: "Q4 2031",
    tenure: "99-year leasehold",
    units: 515,
    avgPsf: 2886,
    launchPsf: 2886,
    landRatePsf: 1084,
    day1Sold: 72,
    totalSold: 72,
    unitMix: [
      { type: "1BR+S", zh: "一房+书房", pct: 20, psf: 2950 },
      { type: "2BR", zh: "二房", pct: 38, psf: 2900 },
      { type: "3BR", zh: "三房", pct: 30, psf: 2860 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2820 },
    ],
    verdict: "outperform",
    verdictLabel: "Bayshore debut",
    zhVerdictLabel: "白沙首盘",
    predictedUplift: [14, 21],
    fairPsf: [2800, 2980],
    rentalYield: 3.7,
    vacancyRisk: "low",
    premiumIndex: 8,
    competingSupply: 980,
    mrtDistance: "Direct to Bayshore MRT (TEL, TE29)",
    schools: ["Bedok Green Primary (within 1km)", "Eastwood Primary"],
    tenantProfile: "East Coast Park lifestyle · TEL commuters to CBD",
    highlights: [
      { tone: "success", en: "Launched Apr 25 2026 — 371 of 515 units sold (72%) at avg $2,886 PSF. Over 70% of units are sea-facing.", zh: "2026年4月25日开盘，371套售出（72%），均价$2,886尺价，逾七成单位朝海。" },
      { tone: "success", en: "Direct to Bayshore MRT (TEL) — first new-launch condo in the Bayshore precinct (former Lagoon View HUDC).", zh: "直连白沙地铁站，白沙区首个新盘（前龙湾苑集体出售）。" },
      { tone: "info", en: "Adjacent to East Coast Park — thin new-launch pipeline in corridor supports medium-term pricing.", zh: "毗邻东海岸公园，走廊内新盘稀缺，中期价格具支撑。" },
    ],
  },

  {
    id: "tengah-garden-residences",
    name: "Tengah Garden Residences",
    zhName: "登加花园苑",
    status: "launched",
    district: "D22 · Tengah",
    zhDistrict: "登加",
    region: "OCR West",
    developer: "Hong Leong Holdings · GuocoLand · CSC Land",
    zhDeveloper: "丰隆控股·国浩·建华",
    launchDate: "Apr 2026",
    topDate: "Q3 2030",
    tenure: "99-year leasehold",
    units: 863,
    avgPsf: 2120,
    launchPsf: 1779,
    landRatePsf: 842,
    day1Sold: 99,
    totalSold: 99,
    unitMix: [
      { type: "2BR", zh: "二房", pct: 30, psf: 1950 },
      { type: "3BR", zh: "三房", pct: 42, psf: 2100 },
      { type: "4BR+", zh: "四房以上", pct: 28, psf: 2280 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [20, 32],
    fairPsf: [1980, 2180],
    rentalYield: 4.0,
    vacancyRisk: "low",
    premiumIndex: 6,
    competingSupply: 1200,
    newTown: true,
    mrtDistance: "Adjacent to Hong Kah MRT (Jurong Region Line)",
    schools: ["Tengah Primary (within 1km)", "Bukit Batok Secondary"],
    tenantProfile: "HDB upgraders · Jurong Lake District workers · JTC Tengah residents",
    highlights: [
      { tone: "success", en: "99% sold on day 1 (853 of 863 units) — strongest launch of 2026. Starting from $1,779 PSF, avg $2,120 PSF.", zh: "首日去化99%（853套），2026年最强开盘。起价$1,779尺价，均价$2,120。" },
      { tone: "success", en: "Tengah's first private condo — adjacent Hong Kah MRT (Jurong Region Line), near upcoming Jurong Lake District.", zh: "登加新镇首个私宅，毗邻红卡地铁站，近裕廊湖区未来开发。" },
      { tone: "info", en: "Mass-market pricing at $2,120 PSF avg — below OCR median, strong HDB-upgrader demand from surrounding BTO estates.", zh: "大众市场价格$2,120均价，低于中部外围区中位数，组屋升级者需求强劲。" },
    ],
  },

  /* ─────────────────  LAUNCHED (misc 2025) ───────────────── */

  {
    id: "bagnall-haus",
    name: "Bagnall Haus",
    zhName: "百纳豪斯",
    status: "launched",
    district: "D16 · Upper East Coast",
    zhDistrict: "上东海岸",
    region: "OCR East",
    developer: "Roxy-Pacific Holdings",
    zhDeveloper: "洛克太平洋",
    launchDate: "Jan 2025",
    topDate: "Q4 2027",
    tenure: "Freehold",
    units: 113,
    avgPsf: 2490,
    launchPsf: 2490,
    landRatePsf: 1107,
    day1Sold: 63,
    totalSold: 75,
    unitMix: [
      { type: "2BR", zh: "二房", pct: 28, psf: 2560 },
      { type: "3BR", zh: "三房", pct: 42, psf: 2490 },
      { type: "4BR+", zh: "四房以上", pct: 30, psf: 2420 },
    ],
    verdict: "neutral",
    verdictLabel: "Neutral",
    zhVerdictLabel: "横盘观望",
    predictedUplift: [6, 12],
    fairPsf: [2360, 2560],
    rentalYield: 3.6,
    vacancyRisk: "low",
    premiumIndex: 8,
    competingSupply: 1180,
    mrtDistance: "~500m to Upper Changi MRT (DTL)",
    schools: ["St. Anthony's Primary", "Temasek Secondary"],
    tenantProfile: "East-end professionals · Changi Business Park commuters",
    highlights: [
      { tone: "success", en: "Rare freehold on Upper East Coast Road — 71 of 113 units (63%) sold at launch at $2,490 PSF.", zh: "上东海岸路稀缺永久地契，开盘去化63%，均价$2,490。" },
      { tone: "info", en: "Former Bagnall Court en-bloc — boutique 113-unit project with large floor plans.", zh: "前百纳苑集体出售地块，113套精品项目，大户型为主。" },
      { tone: "info", en: "Near Upper Changi DTL station — proximity to Changi Business Park and East Coast Park.", zh: "邻近上樟宜地铁站，靠近樟宜商业园及东海岸公园。" },
    ],
  },

  {
    id: "aurea",
    name: "Aurea",
    zhName: "金禧",
    status: "launched",
    district: "D7 · Beach Road",
    zhDistrict: "美芝路",
    region: "RCR",
    developer: "Far East Org · Perennial · Sino Land",
    zhDeveloper: "远东机构·丰盛控股·信和置地",
    launchDate: "Mar 2025",
    topDate: "Q2 2027",
    tenure: "Freehold",
    units: 188,
    avgPsf: 3005,
    launchPsf: 3005,
    landRatePsf: 1820,
    day1Sold: 12,
    totalSold: 35,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 22, psf: 3100 },
      { type: "2BR", zh: "二房", pct: 40, psf: 3020 },
      { type: "3BR", zh: "三房", pct: 28, psf: 2960 },
      { type: "4BR+", zh: "四房以上", pct: 10, psf: 2890 },
    ],
    verdict: "neutral",
    verdictLabel: "Selective demand",
    zhVerdictLabel: "选择性需求",
    predictedUplift: [4, 10],
    fairPsf: [2800, 3100],
    rentalYield: 3.0,
    vacancyRisk: "medium",
    premiumIndex: 12,
    competingSupply: 820,
    mrtDistance: "~350m to Nicoll Highway MRT (CCL)",
    schools: ["St. Joseph's Institution", "Victoria School"],
    tenantProfile: "Heritage / lifestyle buyers · CBD & Marina expat professionals",
    highlights: [
      { tone: "info", en: "Iconic conserved Golden Mile Complex — mixed residential/commercial, freehold.", zh: "标志性保育金禧大厦，住商混合，永久地契。" },
      { tone: "warning", en: "Low day-1 take-up (~12%, 23 units at $3,005 PSF) — pricing tests top of RCR market.", zh: "首日去化仅约12%，均价$3,005尺价，定价接近RCR上限。" },
      { tone: "info", en: "Beach Road heritage precinct undergoing major rejuvenation — unique conservation asset.", zh: "美芝路历史街区正大规模更新，稀缺保育资产。" },
    ],
  },

  {
    id: "one-marina-gardens",
    name: "One Marina Gardens",
    zhName: "滨海花园一号",
    status: "launched",
    district: "D1 · Marina South",
    zhDistrict: "滨海南",
    region: "CCR",
    developer: "Kingsford Group",
    zhDeveloper: "金丰集团",
    launchDate: "Apr 2025",
    topDate: "Q1 2030",
    tenure: "99-year leasehold",
    units: 937,
    avgPsf: 2980,
    launchPsf: 2953,
    landRatePsf: 1402,
    day1Sold: 38,
    totalSold: 55,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 30, psf: 3050 },
      { type: "2BR", zh: "二房", pct: 38, psf: 2980 },
      { type: "3BR", zh: "三房", pct: 24, psf: 2920 },
      { type: "4BR+", zh: "四房以上", pct: 8, psf: 2860 },
    ],
    verdict: "neutral",
    verdictLabel: "Slow burn",
    zhVerdictLabel: "缓速去化",
    predictedUplift: [8, 14],
    fairPsf: [2800, 3050],
    rentalYield: 3.2,
    vacancyRisk: "medium",
    premiumIndex: 10,
    competingSupply: 1240,
    mrtDistance: "Adjacent to Marina South MRT (future NSL/TEL interchange)",
    schools: ["Singapore American School (nearby)", "Marina Cove Primary"],
    tenantProfile: "Marina Bay financial district workers · investment-oriented buyers",
    highlights: [
      { tone: "info", en: "First GLS condo in Marina South — pioneering a brand-new precinct next to Gardens by the Bay.", zh: "滨海南区首个政府售地私宅，毗邻滨海花园，开拓全新生活圈。" },
      { tone: "warning", en: "38% day-1 sell-through (353 of 937 units) — precinct newness and pricing tempered demand.", zh: "首日去化仅38%，新区不确定性与定价抑制初期需求。" },
      { tone: "success", en: "Long-term positive — Marina South MRT, Gardens by the Bay East, and CBD proximity.", zh: "长期前景看好，滨海南地铁站、滨海花园东区及CBD近在咫尺。" },
    ],
  },

  {
    id: "upperhouse",
    name: "UpperHouse",
    zhName: "高苑",
    status: "launched",
    district: "D10 · Orchard Boulevard",
    zhDistrict: "乌节大道",
    region: "CCR",
    developer: "UOL Group · Singapore Land Group",
    zhDeveloper: "华业集团·新加坡置地",
    launchDate: "Jul 2025",
    topDate: "Q3 2029",
    tenure: "99-year leasehold",
    units: 301,
    avgPsf: 3350,
    launchPsf: 3350,
    landRatePsf: 1750,
    day1Sold: 54,
    totalSold: 66,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 20, psf: 3480 },
      { type: "2BR", zh: "二房", pct: 38, psf: 3380 },
      { type: "3BR", zh: "三房", pct: 30, psf: 3300 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 3240 },
    ],
    verdict: "neutral",
    verdictLabel: "CCR Premium",
    zhVerdictLabel: "核心区溢价",
    predictedUplift: [6, 12],
    fairPsf: [3100, 3400],
    rentalYield: 3.0,
    vacancyRisk: "medium",
    premiumIndex: 15,
    competingSupply: 980,
    mrtDistance: "~250m to Orchard Boulevard MRT (TEL)",
    schools: ["Raffles Girls' Primary (within 1km)", "ACS International"],
    tenantProfile: "Ultra-high-net-worth buyers · Orchard Road luxury segment",
    highlights: [
      { tone: "info", en: "UOL/SingLand CCR launch at Orchard Boulevard — 162 of 301 units (54%) sold day 1 at avg $3,350 PSF.", zh: "华业/置地乌节大道黄金地段，开盘日去化54%（162套），均价$3,350。" },
      { tone: "info", en: "~250m to Orchard Boulevard MRT (TEL4) — Orchard to CBD in under 12 min.", zh: "距乌节大道地铁站约250米，乌节至CBD仅12分钟。" },
      { tone: "warning", en: "At $3,350 PSF avg, upside more modest vs comparable RCR launches — niche buyer pool.", zh: "均价$3,350尺价处于溢价区间，涨幅空间相比RCR新盘较有限。" },
    ],
  },

  {
    id: "the-robertson-opus",
    name: "The Robertson Opus",
    zhName: "罗伯申作品",
    status: "launched",
    district: "D9 · Robertson Quay",
    zhDistrict: "罗伯申码头",
    region: "CCR",
    developer: "Frasers Property · Sekisui House",
    zhDeveloper: "星狮地产·积水",
    launchDate: "Jul 2025",
    topDate: "Q2 2029",
    tenure: "Freehold",
    units: 348,
    avgPsf: 3360,
    launchPsf: 3360,
    landRatePsf: 1820,
    day1Sold: 41,
    totalSold: 58,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 3460 },
      { type: "2BR", zh: "二房", pct: 40, psf: 3380 },
      { type: "3BR", zh: "三房", pct: 30, psf: 3320 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 3240 },
    ],
    verdict: "neutral",
    verdictLabel: "Freehold CCR",
    zhVerdictLabel: "永久地契CCR",
    predictedUplift: [6, 12],
    fairPsf: [3100, 3450],
    rentalYield: 3.1,
    vacancyRisk: "medium",
    premiumIndex: 14,
    competingSupply: 1180,
    mrtDistance: "~350m to Fort Canning MRT (DTL)",
    schools: ["River Valley Primary (within 1km)", "Anglo-Chinese School (Junior)"],
    tenantProfile: "Expat finance professionals · freehold collectors · Singapore River lifestyle",
    highlights: [
      { tone: "success", en: "Rare freehold D9 at Robertson Quay — 143 of 348 units (41%) sold launch weekend at $3,360 PSF.", zh: "D9罗伯申码头稀缺永久地契，开盘周末去化41%，均价$3,360。" },
      { tone: "info", en: "Frasers-Sekisui House JV — Sekisui's first Singapore project brings Japanese precision design.", zh: "星狮-积水联营，积水首次进军新加坡，日式精工设计。" },
      { tone: "warning", en: "Moderate CCR take-up vs peers — high absolute PSF limits mass-market appeal.", zh: "CCR去化率中等，高尺价限制大众市场吸引力。" },
    ],
  },

  {
    id: "springleaf-residence",
    name: "Springleaf Residence",
    zhName: "春叶居",
    status: "launched",
    district: "D26 · Upper Thomson",
    zhDistrict: "汤申上段",
    region: "OCR North",
    developer: "GuocoLand · Hong Leong Holdings",
    zhDeveloper: "国浩置地·丰隆控股",
    launchDate: "Aug 2025",
    topDate: "Q4 2030",
    tenure: "99-year leasehold",
    units: 941,
    avgPsf: 2210,
    launchPsf: 2175,
    landRatePsf: 940,
    day1Sold: 92,
    totalSold: 96,
    unitMix: [
      { type: "2BR", zh: "二房", pct: 28, psf: 2260 },
      { type: "3BR", zh: "三房", pct: 42, psf: 2200 },
      { type: "4BR+", zh: "四房以上", pct: 30, psf: 2120 },
    ],
    verdict: "outperform",
    verdictLabel: "Outperform",
    zhVerdictLabel: "跑赢大盘",
    predictedUplift: [10, 18],
    fairPsf: [2060, 2260],
    rentalYield: 3.7,
    vacancyRisk: "low",
    premiumIndex: 8,
    competingSupply: 2480,
    mrtDistance: "~200m to Springleaf MRT (TEL)",
    schools: ["Anderson Primary (within 1km)", "Yishun Innova JC"],
    tenantProfile: "North Singapore families · TEL commuters · nature-lifestyle seekers",
    highlights: [
      { tone: "success", en: "870 of 941 units (92%) sold on launch weekend (Aug 15–16, 2025) at avg $2,175 PSF.", zh: "开盘周末售出870/941套（92%），均价$2,175尺价。" },
      { tone: "success", en: "~200m to Springleaf MRT (TEL) — abutting Lower Seletar Reservoir Park greenery.", zh: "距春叶地铁站约200米，毗邻塞勒达水库公园，绿意盎然。" },
      { tone: "info", en: "GuocoLand-Hong Leong JV — same developer team behind Lentor Mansion (2024 bestseller).", zh: "国浩-丰隆联营，与伦多豪庭（2024年畅销盘）为同一发展商团队。" },
    ],
  },

  /* ─────────────────  LAUNCHED (Jan–Feb 2026) ───────────────── */

  {
    id: "newport-residences",
    name: "Newport Residences",
    zhName: "新汇居",
    status: "launched",
    district: "D2 · Shenton Way",
    zhDistrict: "新顿路",
    region: "CCR",
    developer: "CDL",
    zhDeveloper: "城市发展",
    launchDate: "Jan 2026",
    topDate: "Q4 2030",
    tenure: "Freehold",
    units: 246,
    avgPsf: 3100,
    launchPsf: 2923,
    landRatePsf: 2200,
    day1Sold: 57,
    totalSold: 67,
    unitMix: [
      { type: "1BR", zh: "一房", pct: 24, psf: 3200 },
      { type: "2BR", zh: "二房", pct: 38, psf: 3120 },
      { type: "3BR", zh: "三房", pct: 26, psf: 3040 },
      { type: "4BR+", zh: "四房以上", pct: 12, psf: 2960 },
    ],
    verdict: "neutral",
    verdictLabel: "CBD Freehold",
    zhVerdictLabel: "中央商务区永久地契",
    predictedUplift: [7, 13],
    fairPsf: [2900, 3200],
    rentalYield: 3.0,
    vacancyRisk: "medium",
    premiumIndex: 13,
    competingSupply: 820,
    mrtDistance: "~100m to Tanjong Pagar MRT (EWL) · near Maxwell MRT (TEL)",
    schools: ["Cantonment Primary", "Outram Secondary"],
    tenantProfile: "CBD finance & legal professionals · executive pied-à-terre",
    highlights: [
      { tone: "success", en: "CDL freehold in Shenton Way — 140 of 246 units (57%) sold at launch, from $2,923 PSF.", zh: "城市发展新顿路永久地契，开盘去化57%（140套），起价$2,923尺价。" },
      { tone: "success", en: "~100m to Tanjong Pagar MRT — surrounded by financial institutions and F&B clusters.", zh: "距丹戎巴葛地铁站约100米，被金融机构与餐饮圈围绕。" },
      { tone: "info", en: "Mixed-use tower with serviced residences, offices and retail — live-work-play concept.", zh: "住宅、服务式公寓、办公及零售一体化综合开发项目。" },
    ],
  },

  {
    id: "narra-residences",
    name: "Narra Residences",
    zhName: "纳拉居",
    status: "launched",
    district: "D23 · Dairy Farm",
    zhDistrict: "酪农场",
    region: "OCR West",
    developer: "Santarli · Apex Asia · Soon Li Heng · Kay Lim",
    zhDeveloper: "圣地亚里·亚太·顺利兴·基林",
    launchDate: "Feb 2026",
    topDate: "Q3 2029",
    tenure: "99-year leasehold",
    units: 540,
    avgPsf: 2180,
    launchPsf: 2180,
    landRatePsf: 980,
    day1Sold: 25,
    totalSold: 38,
    unitMix: [
      { type: "2BR", zh: "二房", pct: 30, psf: 2240 },
      { type: "3BR", zh: "三房", pct: 42, psf: 2180 },
      { type: "4BR+", zh: "四房以上", pct: 28, psf: 2100 },
    ],
    verdict: "neutral",
    verdictLabel: "Slow take-up",
    zhVerdictLabel: "缓速去化",
    predictedUplift: [4, 9],
    fairPsf: [2050, 2250],
    rentalYield: 3.5,
    vacancyRisk: "medium",
    premiumIndex: 14,
    competingSupply: 1820,
    mrtDistance: "~400m to Hillview MRT (DTL)",
    schools: ["Bukit Panjang Primary", "German European School Singapore"],
    tenantProfile: "West-side HDB upgraders · Hillview / Bukit Timah nature-belt lifestyle",
    highlights: [
      { tone: "warning", en: "~25% sell-through on launch weekend (135 of 540 units at $2,180 PSF) — below market expectations.", zh: "开盘周末去化约25%（135套），均价$2,180，低于市场预期。" },
      { tone: "info", en: "4-party JV at $980 PSF ppr — OCR West Dairy Farm / Hillview precinct.", zh: "四方联营以$980尺价拿地，西部外围区酪农场/景观山地段。" },
      { tone: "info", en: "Greenery-facing units near Rail Corridor and Bukit Timah Nature Reserve.", zh: "部分单位面向绿廊与武吉知马自然保护区，绿化环境优质。" },
    ],
  },

  /* ─────────────────  UPCOMING  ───────────────── */

  {
    id: "bedok-rise",
    name: "Bedok Rise",
    zhName: "勿洛绿境",
    status: "upcoming",
    district: "D16 · Tanah Merah",
    zhDistrict: "红土",
    region: "OCR East",
    developer: "Allgreen Properties",
    zhDeveloper: "永泰置地",
    launchDate: "Preview 2H 2026",
    topDate: "Q1 2030",
    tenure: "99-year leasehold",
    units: 380,
    landRatePsf: 1020,
    fairPsf: [2480, 2660],
    verdict: "watch",
    verdictLabel: "Good value",
    zhVerdictLabel: "性价比高",
    entryScore: 74,
    rentalYield: 3.8,
    vacancyRisk: "low",
    premiumIndex: 7,
    competingSupply: 1240,
    mrtDistance: "500m to Tanah Merah MRT (EWL + Changi Airport Branch)",
    schools: ["Temasek Primary (1.2km)", "Anglican High School"],
    tenantProfile: "Changi Airport corridor workers · East Coast upgraders",
    unitMix: [
      { type: "2BR", zh: "二房", pct: 30, psf: 2620 },
      { type: "3BR", zh: "三房", pct: 42, psf: 2560 },
      { type: "4BR+", zh: "四房以上", pct: 28, psf: 2490 },
    ],
    highlights: [
      { tone: "success", en: "GLS site by Allgreen Properties — indicative $2,480–$2,660 PSF, competitive vs Grand Dunman.", zh: "政府售地地块，永泰置地开发，指导价$2,480–2,660，性价比优于盛港系列。" },
      { tone: "info", en: "500m to Tanah Merah MRT — EWL + Changi Airport Branch dual interchange, rare connectivity.", zh: "500米至红土站，东西线+樟宜机场支线双线换乘，交通优势突出。" },
      { tone: "info", en: "Mature Bedok estate — near Bedok Mall and Eastpoint Mall, strong amenity base.", zh: "勿洛成熟社区，毗邻勿洛广场和东之点商场，生活配套成熟。" },
    ],
  },

  {
    id: "katong-bloom",
    name: "Katong Bloom",
    zhName: "加东花苑",
    status: "upcoming",
    district: "D15 · Tanjong Katong",
    zhDistrict: "丹戎加东",
    region: "OCR East",
    developer: "Frasers Property (indicative)",
    zhDeveloper: "星狮地产（预估）",
    launchDate: "Preview 2H 2026",
    topDate: "Q2 2031",
    tenure: "Freehold",
    units: 228,
    landRatePsf: 1520,
    fairPsf: [2820, 3050],
    verdict: "hot",
    verdictLabel: "Strong entry",
    zhVerdictLabel: "强烈关注",
    entryScore: 86,
    rentalYield: 3.5,
    vacancyRisk: "low",
    premiumIndex: 10,
    competingSupply: 620,
    mrtDistance: "300m to Tanjong Katong MRT (TEL, TE25)",
    schools: ["Tanjong Katong Primary (within 1km)", "CHIJ Katong Primary"],
    tenantProfile: "Freehold collectors · East Coast expat and professional renters",
    unitMix: [
      { type: "1BR", zh: "一房", pct: 18, psf: 3050 },
      { type: "2BR", zh: "二房", pct: 40, psf: 2950 },
      { type: "3BR", zh: "三房", pct: 32, psf: 2870 },
      { type: "4BR+", zh: "四房以上", pct: 10, psf: 2820 },
    ],
    highlights: [
      { tone: "success", en: "Rare freehold in D15 — 300m to Tanjong Katong MRT (TEL). Indicative $2,820–$3,050 PSF.", zh: "D15区稀缺永久地契，距丹戎加东地铁站300米，指导价$2,820–3,050。" },
      { tone: "success", en: "TEL4 operational since 2024 — Tanjong Katong to Orchard in ~20 min, Marina Bay ~15 min.", zh: "汤申-东海岸线4期2024年开通，加东至乌节路约20分钟。" },
      { tone: "info", en: "Limited freehold supply in D15 — last comparable freehold launch was Tembusu Grand (2023).", zh: "D15永久地契供应稀少，上一同类项目为Tembusu Grand（2023年）。" },
    ],
  },
  {
    id: "lentor-gardens-residences",
    name: "Lentor Gardens Residences",
    zhName: "伦多花园居",
    status: "upcoming",
    district: "D26 · Lentor",
    zhDistrict: "伦多",
    region: "OCR North",
    developer: "Kingsford Huray Development",
    zhDeveloper: "金丰华瑞发展",
    launchDate: "Preview Q3 2026",
    topDate: "Q2 2030",
    tenure: "99-year leasehold",
    units: 500,
    landRatePsf: 984,
    fairPsf: [2100, 2300],
    verdict: "watch",
    verdictLabel: "Lentor 7th wave",
    zhVerdictLabel: "伦多第七盘",
    entryScore: 72,
    rentalYield: 3.6,
    vacancyRisk: "medium",
    premiumIndex: 11,
    competingSupply: 2600,
    mrtDistance: "~200m to Lentor MRT (TEL)",
    schools: ["CHIJ St. Nicholas Girls'", "Anderson Primary"],
    tenantProfile: "North-corridor TEL commuters · Lentor estate upgraders",
    unitMix: [
      { type: "2BR", zh: "二房", pct: 30, psf: 2260 },
      { type: "3BR", zh: "三房", pct: 42, psf: 2180 },
      { type: "4BR+", zh: "四房以上", pct: 28, psf: 2100 },
    ],
    highlights: [
      { tone: "info", en: "7th Lentor neighbourhood condo — indicative $2,100–$2,300 PSF, consistent with Lentor cluster pricing.", zh: "伦多区第七个新盘，指导价$2,100–2,300，与伦多系列定价一致。" },
      { tone: "warning", en: "Lentor supply headwind — ~2,600 competing units within 1.5km from previous launches still absorbing.", zh: "伦多供给压力较大，1.5公里内约2,600套前期单位仍在消化中。" },
      { tone: "info", en: "~200m to Lentor MRT (TEL) — same connectivity advantage as prior Lentor launches.", zh: "步行约200米至伦多地铁站，与前期项目交通优势相同。" },
    ],
  },

  {
    id: "chuan-grove",
    name: "Chuan Grove",
    zhName: "泉林居",
    status: "upcoming",
    district: "D19 · Lorong Chuan",
    zhDistrict: "章宜路",
    region: "OCR North-East",
    developer: "Sing Holdings · Sunway MCL",
    zhDeveloper: "新控股·双威美景",
    launchDate: "Preview Q3 2026",
    topDate: "Q4 2030",
    tenure: "99-year leasehold",
    units: 1055,
    landRatePsf: 1355,
    fairPsf: [2400, 2600],
    verdict: "hot",
    verdictLabel: "Direct MRT mega-dev",
    zhVerdictLabel: "地铁上盖超大盘",
    entryScore: 82,
    rentalYield: 3.5,
    vacancyRisk: "low",
    premiumIndex: 9,
    competingSupply: 1240,
    mrtDistance: "Directly above Lorong Chuan MRT (CCL)",
    schools: ["Yangzheng Primary", "St. Gabriel's Secondary"],
    tenantProfile: "CCL commuters · Bishan-AMK-Serangoon estate upgraders",
    unitMix: [
      { type: "2BR", zh: "二房", pct: 28, psf: 2560 },
      { type: "3BR", zh: "三房", pct: 40, psf: 2480 },
      { type: "4BR+", zh: "四房以上", pct: 32, psf: 2400 },
    ],
    highlights: [
      { tone: "success", en: "Directly above Lorong Chuan MRT (CCL) — ~1,055 units integrated mega-development.", zh: "直接建于章宜地铁站（环线）上方，约1,055套超大型综合项目。" },
      { tone: "success", en: "Land won at $1,355 PSF ppr — indicative $2,400–$2,600 PSF, competitive vs RCR peers.", zh: "以$1,355尺价夺地，指导价$2,400–2,600，与RCR新盘具竞争力。" },
      { tone: "info", en: "Sing Holdings-Sunway MCL JV — experienced mixed-use developers with strong track record.", zh: "新控股-双威美景联营，在新加坡拥有丰富综合开发经验。" },
    ],
  },

  {
    id: "holland-link",
    name: "Holland Link",
    zhName: "荷兰绿苑",
    status: "upcoming",
    district: "D10 · Holland Plain",
    zhDistrict: "荷兰平原",
    region: "CCR",
    developer: "Sim Lian Group",
    zhDeveloper: "森联集团",
    launchDate: "Preview Q3–Q4 2026",
    topDate: "Q4 2031",
    tenure: "99-year leasehold",
    units: 235,
    landRatePsf: 1432,
    fairPsf: [2800, 3200],
    verdict: "hot",
    verdictLabel: "New CCR precinct",
    zhVerdictLabel: "CCR新地段",
    entryScore: 83,
    rentalYield: 3.3,
    vacancyRisk: "low",
    premiumIndex: 10,
    competingSupply: 760,
    mrtDistance: "~300m to Holland Village MRT (CCL)",
    schools: ["Henry Park Primary (within 1km)", "Fairfield Methodist Primary"],
    tenantProfile: "CCR lifestyle buyers · NUS / expat families · Holland Village residents",
    unitMix: [
      { type: "2BR", zh: "二房", pct: 30, psf: 3100 },
      { type: "3BR", zh: "三房", pct: 42, psf: 3000 },
      { type: "4BR+", zh: "四房以上", pct: 28, psf: 2880 },
    ],
    highlights: [
      { tone: "success", en: "First launch in new Holland Plain precinct (D10 CCR) — Sim Lian's highest-value site, $1,432 PSF ppr.", zh: "荷兰平原新地段首个项目（D10核心区），森联最高地价地块，$1,432尺价。" },
      { tone: "success", en: "~300m to Holland Village MRT — adjacent to Skye at Holland (99% sold Oct 2025), precinct momentum strong.", zh: "距荷兰村地铁站约300米，毗邻荷兰天际（2025年10月售罄），片区热度高。" },
      { tone: "info", en: "Indicative $2,800–$3,200 PSF — CCR boutique project near Holland Village conservation shophouses.", zh: "指导价$2,800–3,200尺价，毗邻荷兰村保育店屋的精品CCR项目。" },
    ],
  },

  {
    id: "hougang-central",
    name: "Hougang Central",
    zhName: "后港中央",
    status: "upcoming",
    district: "D19 · Hougang",
    zhDistrict: "后港",
    region: "OCR North-East",
    developer: "UOL · CapitaLand Development · SingLand",
    zhDeveloper: "华业·凯德·新加坡置地",
    launchDate: "Preview H2 2026",
    topDate: "Q1 2031",
    tenure: "99-year leasehold",
    units: 830,
    landRatePsf: 1179,
    fairPsf: [2480, 2640],
    verdict: "hot",
    verdictLabel: "Dual-line interchange",
    zhVerdictLabel: "双线换乘大盘",
    entryScore: 85,
    rentalYield: 3.6,
    vacancyRisk: "low",
    premiumIndex: 7,
    competingSupply: 1080,
    mrtDistance: "Directly above Hougang MRT (NEL · future CRL interchange)",
    schools: ["Hougang Primary", "Serangoon Secondary"],
    tenantProfile: "NEL/CRL commuters · North-East HDB upgraders · long-term asset holders",
    unitMix: [
      { type: "2BR", zh: "二房", pct: 28, psf: 2600 },
      { type: "3BR", zh: "三房", pct: 40, psf: 2520 },
      { type: "4BR+", zh: "四房以上", pct: 32, psf: 2440 },
    ],
    highlights: [
      { tone: "success", en: "Above Hougang MRT (NEL + future CRL interchange) — rare dual-line integrated dev, $1.5B land bid ($1,179 PSF ppr).", zh: "建于后港双线换乘站上方（东北线+未来跨岛线），地价$15亿（$1,179尺价）。" },
      { tone: "success", en: "UOL-CapitaLand-SingLand JV — three of Singapore's most experienced condo developers.", zh: "华业-凯德-新加坡置地联营，三家均为新加坡顶级综合开发商。" },
      { tone: "info", en: "Mixed-use development with retail podium, hawker centre, and direct MRT access.", zh: "含商业裙楼、小贩中心及直通地铁的综合开发，长线价值稳固。" },
    ],
  },
];

window.PROJECTS = PROJECTS;
window.PROJECTS_BY_ID = Object.fromEntries(PROJECTS.map(p => [p.id, p]));
